GameData = {["save_version"] = 1, ["language"] = 1, ["network"] = 5, ["networkMax"] = 7, ["overflow"] = 6, ["seed"] = 514131727, ["new_enemies"] = 1, ["new_missions"] = 1, ["new_equip"] = 1, ["difficulty"] = 2, ["new_abilities"] = 0, ["ach_info"] = {["squad"] = "Archive_A", ["trackers"] = {["Detritus_B_2"] = 0, ["Global_Challenge_Power"] = 0, ["Archive_A_1"] = 0, ["Archive_B_2"] = 0, ["Rust_A_2"] = 0, ["Rust_A_3"] = 0, ["Pinnacle_A_3"] = 0, ["Archive_B_1"] = 0, ["Pinnacle_B_3"] = 0, ["Detritus_B_1"] = 0, ["Pinnacle_B_1"] = 0, ["Global_Island_Mechs"] = 5, ["Global_Island_Building"] = 0, ["Squad_Mist_1"] = 0, ["Squad_Bomber_2"] = 0, ["Squad_Spiders_1"] = 0, ["Squad_Mist_2"] = 0, ["Squad_Heat_1"] = 0, ["Squad_Cataclysm_1"] = 0, ["Squad_Cataclysm_2"] = 0, ["Squad_Cataclysm_3"] = 0, },
},


["current"] = {["score"] = 22345, ["time"] = 4235849.500000, ["kills"] = 135, ["damage"] = 0, ["failures"] = 0, ["difficulty"] = 2, ["victory"] = false, ["islands"] = 3, ["squad"] = 0, 
["mechs"] = {"PunchMech", "TankMech", "ArtiMech", },
["colors"] = {0, 0, 0, },
["weapons"] = {"Prime_Punchmech_AB", "Passive_CritDefense", "Brute_Tankmech_A", "Support_Blizzard_AB", "Ranged_Artillerymech_A", "Ranged_SmokeFire", },
["pilot0"] = {["id"] = "Pilot_Pinnacle", ["name"] = "Clare", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 3, ["exp"] = 50, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["pilot1"] = {["id"] = "Pilot_Leader", ["name"] = "Chen Rong", ["name_id"] = "Pilot_Leader_Name", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 11, ["exp"] = 50, ["level"] = 2, ["travel"] = 4, ["final"] = 1, ["starting"] = true, ["last_end"] = 2, },
["pilot2"] = {["id"] = "Pilot_Assassin", ["name"] = "Abe Isamu", ["name_id"] = "Pilot_Assassin_Name", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 2, ["exp"] = 49, ["level"] = 1, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
},
["current_squad"] = 0, ["undosave"] = true, }
 

RegionData = {
["sector"] = 3, ["island"] = -1, ["secret"] = false, 
["island0"] = {["corporation"] = "Corp_Grass", ["id"] = 0, ["secured"] = true, },
["island1"] = {["corporation"] = "Corp_Desert", ["id"] = 1, ["secured"] = false, },
["island2"] = {["corporation"] = "Corp_Snow", ["id"] = 2, ["secured"] = true, },
["island3"] = {["corporation"] = "Corp_Factory", ["id"] = 3, ["secured"] = true, },
["iBattleRegion"] = 20, 
["final_region"] = {["mission"] = "Mission0", ["player"] = {["battle_type"] = 3, ["iCurrentTurn"] = 4, ["iTeamTurn"] = 1, ["iState"] = 0, ["sMission"] = "Mission0", ["iMissionType"] = 1, ["sBriefingMessage"] = "Final_Mission_Briefing", ["podReward"] = CreateEffect({}), ["secret"] = false, ["spawn_needed"] = false, ["env_time"] = 1000, ["actions"] = 0, ["iUndoTurn"] = 0, ["aiState"] = 3, ["aiDelay"] = 0.000000, ["aiSeed"] = 1468379635, ["victory"] = 2, ["undo_pawns"] = {},


["map_data"] = {["version"] = 7, ["dimensions"] = Point( 8, 8 ), ["name"] = "cave4", ["enemy_kills"] = 8, 
["map"] = {{["loc"] = Point( 0, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 1 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 2 ), ["terrain"] = 4, },
{["loc"] = Point( 0, 3 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 0, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 0, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 1, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 1, 1 ), ["terrain"] = 0, },
{["loc"] = Point( 1, 5 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 1, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 2, 0 ), ["terrain"] = 4, ["health_max"] = 2, ["health_min"] = 1, },
{["loc"] = Point( 2, 2 ), ["terrain"] = 3, ["lava"] = true, ["undo_state"] = {["active"] = true, ["neighbor0"] = {["health"] = 5, ["max_health"] = 5, },
["neighbor2"] = {["health"] = 5, ["max_health"] = 5, },
},
},
{["loc"] = Point( 2, 4 ), ["terrain"] = 0, },
{["loc"] = Point( 2, 6 ), ["terrain"] = 0, },
{["loc"] = Point( 3, 0 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 3, 1 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor1"] = {["health"] = 5, ["max_health"] = 5, },
["neighbor2"] = {["health"] = 4, ["max_health"] = 4, },
},
},
{["loc"] = Point( 4, 1 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor3"] = {["health"] = 2, ["max_health"] = 2, },
},
},
{["loc"] = Point( 4, 2 ), ["terrain"] = 0, ["custom"] = "lava_1.png", ["undo_state"] = {["active"] = true, },
},
{["loc"] = Point( 4, 4 ), ["terrain"] = 0, },
{["loc"] = Point( 4, 5 ), ["terrain"] = 2, ["health_max"] = 2, ["health_min"] = 0, ["rubble_type"] = 0, ["undo_state"] = {["terrain"] = 2, ["active"] = true, ["neighbor1"] = {["health"] = 4, ["max_health"] = 4, },
["neighbor2"] = {["health"] = 4, ["max_health"] = 4, },
},
},
{["loc"] = Point( 4, 6 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor1"] = {["health"] = 4, ["max_health"] = 5, },
},
},
{["loc"] = Point( 4, 7 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 5, 1 ), ["terrain"] = 4, },
{["loc"] = Point( 5, 3 ), ["terrain"] = 0, ["custom"] = "lava_1.png", ["undo_state"] = {["active"] = true, ["neighbor0"] = {["health"] = 5, ["max_health"] = 5, },
},
},
{["loc"] = Point( 5, 5 ), ["terrain"] = 0, },
{["loc"] = Point( 5, 6 ), ["terrain"] = 0, ["undo_state"] = {["active"] = true, ["neighbor0"] = {["health"] = 4, ["max_health"] = 4, },
["neighbor3"] = {["health"] = 4, ["max_health"] = 5, },
},
},
{["loc"] = Point( 5, 7 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 6, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 6, 1 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 6, 3 ), ["terrain"] = 1, ["populated"] = 1, ["health_max"] = 2, },
{["loc"] = Point( 6, 6 ), ["terrain"] = 0, },
{["loc"] = Point( 7, 0 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 6 ), ["terrain"] = 3, ["lava"] = true, },
{["loc"] = Point( 7, 7 ), ["terrain"] = 4, ["health_max"] = 2, ["health_min"] = 1, },
},
["cave_tiles"] = {["0"] = {["id"] = "top_L", ["cracked"] = false, ["tentacle"] = false, },
["1"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["2"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["3"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["4"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = false, },
["5"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = false, },
["6"] = {["id"] = "2", ["cracked"] = true, ["tentacle"] = false, },
["7"] = {["id"] = "end", ["cracked"] = false, ["tentacle"] = false, },
["8"] = {["id"] = "top_R", ["cracked"] = false, ["tentacle"] = false, },
["9"] = {["id"] = "2", ["cracked"] = true, ["tentacle"] = false, },
["10"] = {["id"] = "3", ["cracked"] = false, ["tentacle"] = true, },
["11"] = {["id"] = "2", ["cracked"] = true, ["tentacle"] = false, },
["12"] = {["id"] = "2", ["cracked"] = false, ["tentacle"] = true, },
["13"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = true, },
["14"] = {["id"] = "1", ["cracked"] = false, ["tentacle"] = false, },
["15"] = {["id"] = "end", ["cracked"] = false, ["tentacle"] = false, },
},
["spawns"] = {"Hornet2", "Firefly2", "Beetle2", "Beetle2", },
["spawn_ids"] = {4891, 4893, 4896, 4897, },
["spawn_points"] = {Point(3,7), Point(4,1), Point(6,2), Point(6,4), },
["zones"] = {["pylons"] = {Point( 4, 5 ), Point( 5, 7 ), Point( 6, 3 ), Point( 1, 5 ), Point( 0, 3 ), Point( 6, 1 ), Point( 3, 0 ), },
["mountain"] = {Point( 1, 6 ), Point( 2, 7 ), Point( 7, 3 ), Point( 2, 1 ), },
["layer"] = {},
["bomb"] = {Point( 3, 4 ), Point( 2, 3 ), },
["deployment"] = {Point( 3, 3 ), Point( 3, 4 ), Point( 2, 4 ), Point( 2, 3 ), },
["enemy"] = {Point( 6, 5 ), Point( 6, 4 ), Point( 5, 5 ), Point( 4, 1 ), Point( 4, 6 ), Point( 5, 2 ), Point( 6, 2 ), Point( 5, 6 ), Point( 6, 6 ), Point( 3, 7 ), Point( 5, 4 ), Point( 5, 3 ), Point( 4, 0 ), },
},
["tags"] = {"final_cave", "volcano", },


["pawn1"] = {["type"] = "PunchMech", ["name"] = "", ["id"] = 0, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 4, ["iBonusPower"] = 0, ["iUsedBonus"] = 1, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {0, },
["healthPower"] = {0, },
["primary"] = "Prime_Punchmech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, 1, },
["primary_mod2"] = {1, 1, 2, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Passive_CritDefense", ["secondary_power"] = {},
["secondary_power_class"] = false, ["secondary_mod1"] = {0, },
["secondary_mod2"] = {0, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Pinnacle", ["name"] = "Clare", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 3, ["exp"] = 50, ["level"] = 2, ["travel"] = 0, ["final"] = 1, ["starting"] = true, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 3, ["is_corpse"] = true, ["health"] = 4, ["max_health"] = 5, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(4,1), ["iMissionDamage"] = 0, ["location"] = Point(4,1), ["last_location"] = Point(4,2), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(4,1), ["undoReady"] = false, ["iKillCount"] = 15, ["iOwner"] = 0, ["piTarget"] = Point(3,1), ["piOrigin"] = Point(4,1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,1), },


["pawn2"] = {["type"] = "TankMech", ["name"] = "", ["id"] = 1, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 7, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {1, },
["healthPower"] = {0, },
["primary"] = "Brute_Tankmech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, 1, },
["primary_mod2"] = {0, 0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Support_Blizzard", ["secondary_power"] = {1, },
["secondary_power_class"] = false, ["secondary_mod1"] = {1, },
["secondary_mod2"] = {1, 1, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Leader", ["name"] = "Chen Rong", ["name_id"] = "Pilot_Leader_Name", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 11, ["exp"] = 50, ["level"] = 2, ["travel"] = 4, ["final"] = 1, ["starting"] = true, ["last_end"] = 2, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 1, ["is_corpse"] = true, ["health"] = 4, ["max_health"] = 5, ["undo_state"] = {["iStateBonus"] = 1, ["health"] = 4, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(4,6), ["iMissionDamage"] = 0, ["location"] = Point(4,6), ["last_location"] = Point(5,6), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(4,6), ["undoReady"] = false, ["iKillCount"] = 8, ["iOwner"] = 1, ["piTarget"] = Point(4,6), ["piOrigin"] = Point(5,6), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(5,5), },


["pawn3"] = {["type"] = "ArtiMech", ["name"] = "", ["id"] = 2, ["mech"] = true, ["offset"] = 0, 
["reactor"] = {["iNormalPower"] = 0, ["iUsedPower"] = 3, ["iBonusPower"] = 0, ["iUsedBonus"] = 0, ["iUndoPower"] = 0, ["iUsedUndo"] = 0, },
["movePower"] = {1, },
["healthPower"] = {0, },
["primary"] = "Ranged_Artillerymech", ["primary_power"] = {},
["primary_power_class"] = false, ["primary_mod1"] = {1, },
["primary_mod2"] = {0, 0, 0, },
["primary_damaged"] = false, ["primary_starting"] = true, ["primary_uses"] = 1, ["secondary"] = "Ranged_SmokeFire", ["secondary_power"] = {1, },
["secondary_power_class"] = false, ["secondary_mod1"] = {0, 0, },
["secondary_mod2"] = {0, 0, 0, },
["secondary_damaged"] = false, ["secondary_starting"] = true, ["secondary_uses"] = 1, ["pilot"] = {["id"] = "Pilot_Assassin", ["name"] = "Abe Isamu", ["name_id"] = "Pilot_Assassin_Name", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 2, ["exp"] = 49, ["level"] = 1, ["travel"] = 0, ["final"] = 1, ["starting"] = false, },
["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 1, ["is_corpse"] = true, ["health"] = 4, ["max_health"] = 4, ["undo_state"] = {["health"] = 4, ["max_health"] = 4, },
["undo_ready"] = false, ["undo_point"] = Point(3,1), ["iMissionDamage"] = 0, ["location"] = Point(3,1), ["last_location"] = Point(3,2), ["bActive"] = true, ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(3,1), ["undoReady"] = false, ["iKillCount"] = 7, ["iOwner"] = 2, ["piTarget"] = Point(3,5), ["piOrigin"] = Point(3,1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(3,5), },


["pawn4"] = {["type"] = "Scarab2", ["name"] = "", ["id"] = 4836, ["mech"] = false, ["offset"] = 1, ["primary"] = "ScarabAtk2", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(2,6), ["last_location"] = Point(2,7), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4836, ["piTarget"] = Point(4,6), ["piOrigin"] = Point(2,6), ["piQueuedShot"] = Point(4,6), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(4,6), },


["pawn5"] = {["type"] = "Digger2", ["name"] = "", ["id"] = 4876, ["mech"] = false, ["offset"] = 1, ["primary"] = "DiggerAtk2", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 4, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,6), ["last_location"] = Point(5,5), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 1, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4876, ["piTarget"] = Point(5,6), ["piOrigin"] = Point(5,6), ["piQueuedShot"] = Point(5,6), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(5,6), },


["pawn6"] = {["type"] = "Wall", ["name"] = "", ["id"] = 4889, ["mech"] = false, ["offset"] = 0, ["owner"] = 4876, ["iTeamId"] = 2, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 1, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(4,4), ["last_location"] = Point(-1,-1), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 1, ["iTurnsRemaining"] = 2, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4889, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },


["pawn7"] = {["type"] = "Hornet2", ["name"] = "", ["id"] = 4892, ["mech"] = false, ["offset"] = 1, ["primary"] = "HornetAtk2", ["primary_uses"] = 1, ["iTeamId"] = 6, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 4, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(1,1), ["last_location"] = Point(1,0), ["iCurrentWeapon"] = 1, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1953394499, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4892, ["piTarget"] = Point(2,1), ["piOrigin"] = Point(1,1), ["piQueuedShot"] = Point(2,1), ["iQueuedSkill"] = 1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(2,1), },


["pawn8"] = {["type"] = "Wall", ["name"] = "", ["id"] = 4894, ["mech"] = false, ["offset"] = 0, ["owner"] = 4876, ["iTeamId"] = 2, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 1, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(5,5), ["last_location"] = Point(-1,-1), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1667330627, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4894, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },


["pawn9"] = {["type"] = "Wall", ["name"] = "", ["id"] = 4895, ["mech"] = false, ["offset"] = 0, ["owner"] = 4876, ["iTeamId"] = 2, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 1, ["max_health"] = 1, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(6,6), ["last_location"] = Point(-1,-1), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 0, ["iTurnsRemaining"] = 1885433122, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4895, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },


["pawn10"] = {["type"] = "BigBomb", ["name"] = "", ["id"] = 4837, ["mech"] = false, ["offset"] = 0, ["iTeamId"] = 1, ["timebonus"] = false, ["iFaction"] = 0, ["iKills"] = 0, ["is_corpse"] = false, ["health"] = 4, ["max_health"] = 4, ["undo_state"] = {["health"] = 5, ["max_health"] = 5, },
["undo_ready"] = false, ["undo_point"] = Point(-1,-1), ["iMissionDamage"] = 0, ["location"] = Point(2,4), ["last_location"] = Point(2,4), ["iCurrentWeapon"] = 0, ["iTurnCount"] = 4, ["iTurnsRemaining"] = 1, ["undoPosition"] = Point(-1,-1), ["undoReady"] = false, ["iKillCount"] = 0, ["iOwner"] = 4837, ["piTarget"] = Point(-1,-1), ["piOrigin"] = Point(-1,-1), ["piQueuedShot"] = Point(-1,-1), ["iQueuedSkill"] = -1, ["priorityTarget"] = Point(-1,-1), ["targetHistory"] = Point(-1,-1), },
["pawn_count"] = 10, ["blocked_points"] = {Point(0,3), Point(1,5), Point(3,0), Point(5,7), Point(6,1), Point(6,3), },
["blocked_type"] = {2, 2, 2, 2, 2, 2, },
},


},
["state"] = 1, ["name"] = "Volcanic Hive", },
}
 

GAME = { 
["WeaponDeck"] = { 
[31] = "Ranged_ScatterShot", 
[2] = "Prime_Lasermech", 
[8] = "Prime_Areablast", 
[32] = "Ranged_BackShot", 
[33] = "Ranged_Ice", 
[34] = "Ranged_SmokeBlast", 
[35] = "Ranged_RainingVolley", 
[9] = "Prime_Spear", 
[36] = "Ranged_Wide", 
[37] = "Ranged_Dual", 
[38] = "Science_Gravwell", 
[39] = "Science_Swap", 
[10] = "Prime_Leap", 
[40] = "Science_Repulse", 
[41] = "Science_AcidShot", 
[42] = "Science_SmokeDefense", 
[43] = "Science_Shield", 
[11] = "Prime_SpinFist", 
[44] = "Science_FireBeam", 
[45] = "Science_FreezeBeam", 
[46] = "Support_Boosters", 
[3] = "Prime_ShieldBash", 
[12] = "Prime_Sword", 
[48] = "Support_Destruct", 
[49] = "DeploySkill_ShieldTank", 
[50] = "DeploySkill_Tank", 
[51] = "DeploySkill_AcidTank", 
[13] = "Prime_Smash", 
[52] = "DeploySkill_PullTank", 
[53] = "Support_Force", 
[54] = "Support_Repair", 
[55] = "Support_Missiles", 
[14] = "Brute_Jetmech", 
[56] = "Support_Wind", 
[57] = "Passive_FlameImmune", 
[58] = "Passive_Electric", 
[59] = "Passive_MassRepair", 
[15] = "Brute_Mirrorshot", 
[60] = "Passive_Defenses", 
[61] = "Passive_AutoShields", 
[17] = "Brute_Grapple", 
[62] = "Passive_Psions", 
[1] = "Prime_Lightning", 
[63] = "Passive_Boosters", 
[16] = "Brute_PhaseShot", 
[64] = "Passive_Medical", 
[65] = "Passive_FriendlyFire", 
[66] = "Passive_ForceAmp", 
[67] = "Prime_Flamespreader", 
[68] = "Prime_WayTooBig", 
[69] = "Prime_PrismLaser", 
[70] = "Prime_TC_Punt", 
[71] = "Prime_TC_BendBeam", 
[72] = "Prime_TC_Feint", 
[73] = "Prime_KO_Crack", 
[74] = "Brute_KickBack", 
[75] = "Brute_Fracture", 
[76] = "Brute_PierceShot", 
[77] = "Brute_TC_GuidedMissile", 
[78] = "Brute_TC_Ricochet", 
[79] = "Brute_TC_DoubleShot", 
[80] = "Brute_KO_Combo", 
[81] = "Ranged_Crack", 
[82] = "Ranged_DeployBomb", 
[83] = "Ranged_Arachnoid", 
[84] = "Ranged_TC_BounceShot", 
[85] = "Ranged_TC_DoubleArt", 
[86] = "Ranged_KO_Combo", 
[22] = "Brute_Unstable", 
[88] = "Science_MassShift", 
[89] = "Science_TelePush", 
[90] = "Science_Placer", 
[23] = "Brute_Heavyrocket", 
[92] = "Science_TC_Enrage", 
[93] = "Science_TC_SwapOther", 
[6] = "Prime_Shift", 
[24] = "Brute_Splitshot", 
[96] = "Support_GridDefense", 
[97] = "Support_Waterdrill", 
[98] = "Support_TC_GridAtk", 
[25] = "Brute_Bombrun", 
[100] = "Passive_HealingSmoke", 
[101] = "Passive_FireBoost", 
[102] = "Passive_PlayerTurnShield", 
[26] = "Brute_Sonic", 
[18] = "Brute_Shrapnel", 
[19] = "Brute_Sniper", 
[87] = "Science_RainingFire", 
[27] = "Ranged_Rockthrow", 
[91] = "Science_TC_Control", 
[94] = "Science_KO_Crack", 
[7] = "Prime_Flamethrower", 
[28] = "Ranged_Defensestrike", 
[95] = "Support_Confuse", 
[103] = "Passive_VoidShock", 
[99] = "Support_KO_GridCharger", 
[29] = "Ranged_Rocket", 
[21] = "Brute_Beetle", 
[20] = "Brute_Shockblast", 
[5] = "Prime_RocketPunch", 
[30] = "Ranged_Ignite", 
[4] = "Prime_RightHook", 
[47] = "Support_Smoke" 
}, 
["PodWeaponDeck"] = { 
[27] = "DeploySkill_AcidTank", 
[31] = "Support_Missiles", 
[38] = "Passive_Psions", 
[46] = "Prime_TC_Feint", 
[54] = "Science_Placer", 
[62] = "Passive_FireBoost", 
[5] = "Prime_Sword", 
[6] = "Prime_Smash", 
[7] = "Brute_Grapple", 
[8] = "Brute_Sniper", 
[39] = "Passive_Boosters", 
[12] = "Brute_Bombrun", 
[55] = "Science_TC_Enrage", 
[16] = "Ranged_RainingVolley", 
[20] = "Science_FireBeam", 
[24] = "Support_Destruct", 
[28] = "DeploySkill_PullTank", 
[32] = "Support_Wind", 
[40] = "Passive_Medical", 
[48] = "Brute_TC_GuidedMissile", 
[56] = "Support_Confuse", 
[64] = "Passive_VoidShock", 
[63] = "Passive_PlayerTurnShield", 
[47] = "Brute_Fracture", 
[4] = "Prime_SpinFist", 
[33] = "Passive_FlameImmune", 
[41] = "Passive_FriendlyFire", 
[49] = "Brute_KO_Combo", 
[57] = "Support_GridDefense", 
[17] = "Ranged_Dual", 
[21] = "Science_FreezeBeam", 
[25] = "DeploySkill_ShieldTank", 
[29] = "Support_Force", 
[34] = "Passive_Electric", 
[42] = "Passive_ForceAmp", 
[50] = "Ranged_TC_BounceShot", 
[58] = "Support_Waterdrill", 
[1] = "Prime_Areablast", 
[10] = "Brute_Beetle", 
[9] = "Brute_Shockblast", 
[11] = "Brute_Heavyrocket", 
[35] = "Passive_MassRepair", 
[43] = "Prime_WayTooBig", 
[51] = "Ranged_TC_DoubleArt", 
[59] = "Support_TC_GridAtk", 
[18] = "Science_SmokeDefense", 
[22] = "Support_Boosters", 
[26] = "DeploySkill_Tank", 
[30] = "Support_Repair", 
[36] = "Passive_Defenses", 
[44] = "Prime_PrismLaser", 
[52] = "Ranged_KO_Combo", 
[60] = "Support_KO_GridCharger", 
[15] = "Ranged_SmokeBlast", 
[14] = "Ranged_Ice", 
[3] = "Prime_Leap", 
[13] = "Brute_Sonic", 
[37] = "Passive_AutoShields", 
[45] = "Prime_TC_BendBeam", 
[53] = "Science_TelePush", 
[61] = "Passive_HealingSmoke", 
[19] = "Science_Shield", 
[23] = "Support_Smoke", 
[2] = "Prime_Spear" 
}, 
["PilotDeck"] = { 
[13] = "Pilot_Delusional", 
[7] = "Pilot_Genius", 
[1] = "Pilot_Original", 
[2] = "Pilot_Youth", 
[4] = "Pilot_Aquatic", 
[8] = "Pilot_Miner", 
[9] = "Pilot_Recycler", 
[5] = "Pilot_Medic", 
[10] = "Pilot_Repairman", 
[11] = "Pilot_Caretaker", 
[6] = "Pilot_Hotshot", 
[12] = "Pilot_Chemical", 
[3] = "Pilot_Warrior" 
}, 
["SeenPilots"] = { 
[6] = "Pilot_Assassin", 
[2] = "Pilot_Pinnacle", 
[3] = "Pilot_Archive", 
[1] = "Pilot_Leader", 
[4] = "Pilot_Soldier", 
[5] = "Pilot_Arrogant" 
}, 
["PodDeck"] = { 
[6] = { 
["cores"] = 1, 
["pilot"] = "random" 
}, 
[2] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[3] = { 
["cores"] = 1, 
["weapon"] = "random" 
}, 
[1] = { 
["cores"] = 1 
}, 
[4] = { 
["cores"] = 1, 
["pilot"] = "random" 
}, 
[5] = { 
["cores"] = 1, 
["pilot"] = "random" 
} 
}, 
["Bosses"] = { 
[1] = "Mission_SpiderBoss", 
[2] = "Mission_BlobBoss", 
[4] = "Mission_BeetleBoss", 
[3] = "Mission_CrabBoss" 
}, 
["Enemies"] = { 
[1] = { 
[6] = "Starfish", 
[2] = "Hornet", 
[3] = "Firefly", 
[1] = "Bouncer", 
[4] = "Jelly_Armor", 
[5] = "Beetle", 
["island"] = 1 
}, 
[2] = { 
[6] = "Dung", 
[2] = "Burnbug", 
[3] = "Scorpion", 
[1] = "Moth", 
[4] = "Jelly_Explode", 
[5] = "Shaman", 
["island"] = 2 
}, 
[4] = { 
[6] = "Spider", 
[2] = "Leaper", 
[3] = "Mosquito", 
[1] = "Bouncer", 
[4] = "Jelly_Regen", 
[5] = "Crab", 
["island"] = 4 
}, 
[3] = { 
[6] = "Digger", 
[2] = "Leaper", 
[3] = "Scarab", 
[1] = "Mosquito", 
[4] = "Jelly_Boost", 
[5] = "Burrower", 
["island"] = 3 
} 
}, 
["Missions"] = { 
[0] = { 
["Spawner"] = { 
["pawn_counts"] = { 
["Jelly_Lava"] = 1, 
["Digger"] = 1, 
["Blobber"] = 1, 
["Crab"] = 2, 
["Scarab"] = 2, 
["Beetle"] = 2, 
["Firefly"] = 1, 
["Scorpion"] = 3, 
["Leaper"] = 2, 
["Hornet"] = 3 
}, 
["used_bosses"] = 0, 
["spawn_island"] = 5, 
["curr_weakRatio"] = { 
[1] = 1, 
[2] = 1 
}, 
["num_bosses"] = 0, 
["curr_upgradeRatio"] = { 
[1] = 1, 
[2] = 1 
}, 
["num_spawns"] = 14, 
["upgrade_streak"] = 6 
}, 
["LiveEnvironment"] = { 
["Locations"] = { 
[1] = Point( 7, 5 ), 
[2] = Point( 6, 5 ), 
[3] = Point( 5, 5 ), 
[4] = Point( 4, 5 ), 
[5] = Point( 3, 5 ), 
[6] = Point( 2, 5 ), 
[7] = Point( 1, 4 ), 
[8] = Point( 1, 3 ), 
[9] = Point( 1, 2 ), 
[10] = Point( 0, 2 ) 
}, 
["LavaPath"] = { 
[6] = Point( 2, 2 ), 
[2] = Point( 6, 2 ), 
[8] = Point( 0, 2 ), 
[3] = Point( 5, 2 ), 
[1] = Point( 7, 2 ), 
[4] = Point( 4, 2 ), 
[5] = Point( 3, 2 ), 
[7] = Point( 1, 2 ) 
}, 
["Instant"] = true, 
["EndEffect"] = true, 
["Planned"] = { 
[1] = Point( 7, 5 ), 
[2] = Point( 6, 5 ), 
[3] = Point( 5, 5 ), 
[4] = Point( 4, 5 ), 
[5] = Point( 3, 5 ), 
[6] = Point( 2, 5 ), 
[7] = Point( 1, 4 ), 
[8] = Point( 1, 3 ), 
[9] = Point( 1, 2 ), 
[10] = Point( 0, 2 ) 
}, 
["Phase"] = 4, 
["Mode"] = 2, 
["StartEffect"] = true, 
["WaterTarget"] = false 
}, 
["ID"] = "Mission_Final_Cave", 
["VoiceEvents"] = { 
}, 
["BonusObjs"] = { 
} 
} 
}, 
["Island"] = 1 
}

 

SquadData = {
["money"] = 0, ["cores"] = 0, ["bIsFavor"] = false, ["repairs"] = 0, ["CorpReward"] = {CreateEffect({weapon = "Support_Refrigerate",}), CreateEffect({skill1 = "Health",skill2 = "Grid",pilot = "Pilot_Assassin",stock = 0,}), CreateEffect({power = 2,}), },
["RewardClaimed"] = true, 
["skip_pawns"] = true, 

["storage_size"] = 3, ["CorpStore"] = {CreateEffect({weapon = "Science_Pullmech",money = -2,}), CreateEffect({weapon = "Prime_Rockmech",money = -2,}), CreateEffect({weapon = "Support_SmokeDrop",money = -2,}), CreateEffect({weapon = "Passive_Burrows",money = -2,}), CreateEffect({money = -3,stock = -1,cores = 1,}), CreateEffect({money = -1,power = 1,stock = -1,}), },
["island_store_count"] = 2, ["store_undo_size"] = 6, ["store_undo_0"] = {["Weapon"] = "Science_LocalShield", ["Effect"] = CreateEffect({money = -1,}), },
["store_undo_1"] = {["Effect"] = CreateEffect({money = 3,stock = -1,cores = -1,}), },
["store_undo_2"] = {["Effect"] = CreateEffect({money = 3,stock = -1,cores = -1,}), },
["store_undo_3"] = {["Effect"] = CreateEffect({money = 3,stock = -1,cores = -1,}), },
["store_undo_4"] = {["Pilot"] = {["id"] = "Pilot_Archive", ["name"] = "Ana Singh", ["name_id"] = "", ["renamed"] = false, ["skill1"] = 0, ["skill2"] = 2, ["exp"] = 15, ["level"] = 2, ["travel"] = 0, ["final"] = 0, ["starting"] = true, },
["Effect"] = CreateEffect({money = -1,}), },
["store_undo_5"] = {["Effect"] = CreateEffect({money = 1,stock = -1,grid = -2,}), },
}
 

